language: node_js
node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run lint

deploy:
  provider: heroku
  app: test-task-wt
  api_key:
    secure: IEI7Zv+n8USSr8NopvrouZGk0u9Wz6TzSQcLEGqAOgqIL4pPSITL13J54ADTtzBMBXcmko18PxIEq6MFXRP0RmsKYtp6WSKYuu5SOdj/M2R9iY2ZYIlyb4rrQQH42nYTtbv+9AmWhNRYHI6YamA+hW1esbkycHHM1ygkHSF/ZIQOKOM15GERyRLp+HLR9EQB0x7zA//mJibcdbW3yd2owePg4GYQXKVuVoMsyCT4Yc+CHImKHrCvcRgEPtNKYp5e15lEnnwlvazq5tkeVB0sceuK4g24IKZcQzhikEe9nTSDNsxrMIPF1MtZGziQEjyPZmK6t5Y63Wn2zvWEsIy0yf8cxwCBRFP6w/hlVXA1hqIVrAlHkh3fqTkiKqHlEjFZMOsTjarPmmsjd/XslXkz7QpNeNZgDWUbmxLqNyjG4NVEwEaRovO2zs4KKRWHvbW336hIcFu3G3JEt8p9y/llsUTYdbwlflpz43MI37vm4SaSS8hPuhuTbFTe+UUl6zIjtNvtxjD01izt4TacbujpUSH47H13Q3BbyzozMK8PXtyDJy+7A8bbjYhpag6fgHxtDxCdve6SNepjLKrvlLnV0RvKVov7fX5oASI6Y4GE5sS/Y2DuZ7yTV+P9f5vALMW77DQRRS4sCsvHSlDQN2yfncl/W0Q8ZOoY9Urp/9lUC0g=
