export default {
  "data": {
    "id": 76996763,
    "node_id": "MDEwOlJlcG9zaXRvcnk3Njk5Njc2Mw==",
    "name": "react-redux-typescript-guide",
    "full_name": "piotrwitek/react-redux-typescript-guide",
    "private": false,
    "owner": {
      "login": "piotrwitek",
      "id": 739075,
      "node_id": "MDQ6VXNlcjczOTA3NQ==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/739075?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/piotrwitek",
      "html_url": "https://github.com/piotrwitek",
      "followers_url": "https://api.github.com/users/piotrwitek/followers",
      "following_url": "https://api.github.com/users/piotrwitek/following{/other_user}",
      "gists_url": "https://api.github.com/users/piotrwitek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/piotrwitek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/piotrwitek/subscriptions",
      "organizations_url": "https://api.github.com/users/piotrwitek/orgs",
      "repos_url": "https://api.github.com/users/piotrwitek/repos",
      "events_url": "https://api.github.com/users/piotrwitek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/piotrwitek/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/piotrwitek/react-redux-typescript-guide",
    "description": "The complete guide to static typing in \"React & Redux\" apps using TypeScript",
    "fork": false,
    "url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide",
    "forks_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/forks",
    "keys_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/teams",
    "hooks_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/hooks",
    "issue_events_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/issues/events{/number}",
    "events_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/events",
    "assignees_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/assignees{/user}",
    "branches_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/branches{/branch}",
    "tags_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/tags",
    "blobs_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/languages",
    "stargazers_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/stargazers",
    "contributors_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/contributors",
    "subscribers_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/subscribers",
    "subscription_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/subscription",
    "commits_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/contents/{+path}",
    "compare_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/merges",
    "archive_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/downloads",
    "issues_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/issues{/number}",
    "pulls_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/labels{/name}",
    "releases_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/releases{/id}",
    "deployments_url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide/deployments",
    "created_at": "2016-12-20T22:35:36Z",
    "updated_at": "2019-02-25T10:20:06Z",
    "pushed_at": "2019-02-22T11:21:13Z",
    "git_url": "git://github.com/piotrwitek/react-redux-typescript-guide.git",
    "ssh_url": "git@github.com:piotrwitek/react-redux-typescript-guide.git",
    "clone_url": "https://github.com/piotrwitek/react-redux-typescript-guide.git",
    "svn_url": "https://github.com/piotrwitek/react-redux-typescript-guide",
    "homepage": "https://piotrwitek.github.io/react-redux-typescript-guide/",
    "size": 1484,
    "stargazers_count": 4939,
    "watchers_count": 4939,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 265,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 26,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 265,
    "open_issues": 26,
    "watchers": 4939,
    "default_branch": "master",
    "network_count": 265,
    "subscribers_count": 111
  },
  "status": 200,
  "statusText": "OK",
  "headers": {
    "cache-control": "public, max-age=60, s-maxage=60",
    "content-type": "application/json; charset=utf-8",
    "etag": "W/\"15c57da9e552f7a35742b63e20ebd731\"",
    "last-modified": "Mon, 25 Feb 2019 10:20:06 GMT",
    "x-github-media-type": "github.v3; param=raw; format=json",
    "x-ratelimit-limit": "60",
    "x-ratelimit-remaining": "42",
    "x-ratelimit-reset": "1551100544"
  },
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/vnd.github.v3.raw+json"
    },
    "method": "get",
    "baseURL": "https://api.github.com/repos/",
    "url": "https://api.github.com/repos/piotrwitek/react-redux-typescript-guide"
  },
  "request": {}
}